services:
  backend:
    build: ./backend
    container_name: kodi_fat32_splitter_backend
    ports:
      - "8000:8000"
    volumes:
      - "C:/Users/raido/OneDrive/Documents/Development/rar splitter v2/data:/data"
      - "./config:/config"
    restart: unless-stopped
    environment:
      - OIDC_AUTHORITY=${OIDC_AUTHORITY}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}

  frontend:
    build: ./frontend
    container_name: kodi_fat32_splitter_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - OIDC_AUTH=${OIDC_AUTH:-true}
      - OIDC_AUTHORITY=${OIDC_AUTHORITY}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_LOGOUT=${OIDC_LOGOUT}
    restart: unless-stopped
