services:
  backend:
    build: ./backend
    container_name: kodi_fat32_splitter_backend
    ports:
      - "8000:8000"
    volumes:
      - "C:\\Users\\raido\\OneDrive\\Documents\\Development\\rar splitter v2\\data:/data"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: kodi_fat32_splitter_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
